version: '3.8'

networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  website01:
    image: nginx-site1
    #ports:
    #  - 8081:80
    networks:
      - nginx_net

  website02:
    image: nginx-site2
    #ports:
    #  - 8082:80
    networks:
      - nginx_net

  website03:
    image: nginx-site3
    #ports:
    #  - 8083:80
    networks:
      - nginx_net
